"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.app = void 0;
const functions_1 = require("@azure/functions");
Object.defineProperty(exports, "app", { enumerable: true, get: function () { return functions_1.app; } });
// import './functions/health';
require("./functions/oauth");
require("./functions/tenants");
// import './functions/thirdPartyAPIs';
// import './functions/parBrinkConfigurations';
// import './functions/parBrinkDashboard';
// import './functions/parBrinkEnhanced';
// import './functions/parBrinkToUkgETL';
// import './functions/simpleTest';
// import './functions/tenantCredentialsV2';
// import './functions/tenantsV2';
// import './functions/testDbConnection';
// import './functions/thirdPartyAPISimple';
// import './functions/ukgReadyAPI';
// import './functions/tipToWebTable';
// import './functions/tenantToWebTable';
require("./functions/tenantEndpoints");
// import './functions/tipDataExtract';
// import './functions/parBrinkClockedIn';
// import './functions/parBrinkDebugSales';
// import './functions/ukgTenantDashboard';
// import './functions/employeeDataSync';
// import './functions/employeeData';
// import './functions/employeeAuthFunctions';
// import './functions/employeeManagementFunctions';
// import './functions/testCacheSimple';
// import './functions/testCacheRefreshSimple';
// import './functions/ukgEmployeeCacheRefresh';
// import './functions/ukgClockedInDashboardCached';
// import './functions/ukgTimeEntriesSync';
// import './functions/ukgEmployeeDetailsSync';
// import './functions/ukgGenericSync';
// import './functions/ukgMasterScheduler';
// import './functions/ukgTodaysPunchesDashboard';
// import './functions/maintenanceStatus';
// import './functions/testCacheRefreshDebug';
// import './functions/authFunctions';
// import './functions/createClockedInCacheTable';
// import './functions/dashboardConfigurationFunctions';
// import './functions/multiStoreLaborStats';
// import './functions/multiStoreSalesStats';
// import './functions/brinkSalesFromDatabase';
// import './functions/syncConfigurationManagement';
// import './functions/manualSyncTrigger';
// import './functions/payPeriodMonitor';
// import './functions/weeklyDataSync';
// import './functions/brinkTipsFromDatabase';
// import './functions/laborCostCalculation';
// import './functions/multiSourceDashboard';
// import './functions/multiSourceDashboardPublic';
// import './functions/populateMultiSourceMerge';
// import './functions/multiSourceMergeHealth';
// import './functions/multiSourceMergeTimer';
// import './functions/testCostCenterApi';
// import './functions/userManagement';
// import './functions/storeAuthFunctions';
require("./functions/entraAuth");
require("./functions/rkUpload");
//# sourceMappingURL=app.js.map