import { app } from '@azure/functions';

// import './functions/health';
import './functions/oauth';
import './functions/tenants';
// import './functions/thirdPartyAPIs';
// import './functions/parBrinkConfigurations';
// import './functions/parBrinkDashboard';
// import './functions/parBrinkEnhanced';
// import './functions/parBrinkToUkgETL';
// import './functions/simpleTest';
// import './functions/tenantCredentialsV2';
// import './functions/tenantsV2';
// import './functions/testDbConnection';
// import './functions/thirdPartyAPISimple';
// import './functions/ukgReadyAPI';
// import './functions/tipToWebTable';
// import './functions/tenantToWebTable';
import './functions/tenantEndpoints';
// import './functions/tipDataExtract';
// import './functions/parBrinkClockedIn';
// import './functions/parBrinkDebugSales';
// import './functions/ukgTenantDashboard';
// import './functions/employeeDataSync';
// import './functions/employeeData';
// import './functions/employeeAuthFunctions';
// import './functions/employeeManagementFunctions';
// import './functions/testCacheSimple';
// import './functions/testCacheRefreshSimple';
// import './functions/ukgEmployeeCacheRefresh';
// import './functions/ukgClockedInDashboardCached';
// import './functions/ukgTimeEntriesSync';
// import './functions/ukgEmployeeDetailsSync';
// import './functions/ukgGenericSync';
// import './functions/ukgMasterScheduler';
// import './functions/ukgTodaysPunchesDashboard';
// import './functions/maintenanceStatus';
// import './functions/testCacheRefreshDebug';
// import './functions/authFunctions';
// import './functions/createClockedInCacheTable';
// import './functions/dashboardConfigurationFunctions';
// import './functions/multiStoreLaborStats';
// import './functions/multiStoreSalesStats';
// import './functions/brinkSalesFromDatabase';
// import './functions/syncConfigurationManagement';
// import './functions/manualSyncTrigger';
// import './functions/payPeriodMonitor';
// import './functions/weeklyDataSync';
// import './functions/brinkTipsFromDatabase';
// import './functions/laborCostCalculation';
// import './functions/multiSourceDashboard';
// import './functions/multiSourceDashboardPublic';
// import './functions/populateMultiSourceMerge';
// import './functions/multiSourceMergeHealth';
// import './functions/multiSourceMergeTimer';
// import './functions/testCostCenterApi';
// import './functions/userManagement';
// import './functions/storeAuthFunctions';
import './functions/entraAuth';
import './functions/rkUpload';
import './functions/sftp';
import './functions/sftpConfigurations';
import './functions/passwordsApi';
// import './functions/parBrinkXmlTest';
// import './functions/refreshClockedInDashboard';
// import './functions/simplifiedClockedInDashboard';
// import './functions/ukgEndpointTester';
// import './functions/ukgTimePunch';

// Export the app for Azure Functions v4
export { app };